files: |
  (?x)^(
    mservice/|
    pytests/
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
      - id: mypy
        args: [ --config-file, mypy.ini ]
        types: [python]
        additional_dependencies: [pydantic==2.0.2]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.245'
    hooks:
      - id: ruff
        args: ['--fix']
        types: [python]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
