version: '3.8'
x-defs:
  main_server: &main_server
    image: url-monitor-server:latest
    restart: unless-stopped
    command: server
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - prod.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

services:
  migrate:
    <<: *main_server
    restart: on-failure
    command: [ 'migrate' ]

  api:
    <<: *main_server
    ports:
      - "8000:8000"
    command: [ 'server' ]

  worker:
    <<: *main_server
    command: [ 'worker' ]